name: Build XRZ Chat APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Android
        uses: android-actions/setup-android@v3

      - name: Install Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.9'

      - name: Build APK
        run: gradle assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: XRZ-Chat
          path: app/build/outputs/apk/release/*.apk
